host = "0.0.0.0"
port = 8282

DatabaseType = "postgres"
PostgresHost = "ep-raspy-frog-aoq69tsq.c-2.ap-southeast-1.aws.neon.tech"
PostgresPort = "5432"
PostgresDatabase = "neondb"
PostgresUser = "neondb_owner"
PostgresPass = "npg_mwVyg1a7NKPH"
PostgresSSLMode = "require"
